"""Canonical team alias table — data Source of Truth for EntityResolver.

Migrated from copilot_engine._TEAM_ALIASES (Phase 5A).
Import TEAM_ALIASES; do not duplicate this table elsewhere.
"""

from __future__ import annotations

TEAM_ALIASES: dict[str, str] = {
    # European clubs
    "psg": "Paris Saint-Germain",
    "paris sg": "Paris Saint-Germain",
    "paris saint germain": "Paris Saint-Germain",
    "man united": "Manchester United",
    "man utd": "Manchester United",
    "manchester utd": "Manchester United",
    "manchester united": "Manchester United",
    "man u": "Manchester United",
    "man city": "Manchester City",
    "manchester city": "Manchester City",
    "mancity": "Manchester City",
    "manutd": "Manchester United",
    "realmadrid": "Real Madrid",
    "atleticomineiro": "Atletico Mineiro",
    "atleticomadrid": "Atletico Madrid",
    "acmilan": "AC Milan",
    "intermilan": "Inter Milan",
    "saopaulo": "Sao Paulo",
    "bayernmunich": "Bayern Munich",
    "arsenal": "Arsenal",
    "afc arsenal": "Arsenal",
    "chelsea": "Chelsea",
    "chelsea fc": "Chelsea",
    "liverpool": "Liverpool",
    "liverpool fc": "Liverpool",
    "newcastle": "Newcastle",
    "newcastle united": "Newcastle",
    "west ham": "West Ham",
    "aston villa": "Aston Villa",
    "brighton": "Brighton",
    "wolves": "Wolves",
    "everton": "Everton",
    "leicester": "Leicester",
    "atletico madrid": "Atletico Madrid",
    "atm": "Atletico Madrid",
    "atletico": "Atletico Madrid",
    "real": "Real Madrid",
    "real madrid": "Real Madrid",
    "barca": "Barcelona",
    "barcelona": "Barcelona",
    "fcb": "Barcelona",
    "spurs": "Tottenham",
    "tottenham": "Tottenham",
    "tottenham hotspur": "Tottenham",
    "dortmund": "Borussia Dortmund",
    "bvb": "Borussia Dortmund",
    "bayern": "Bayern Munich",
    "bayern munich": "Bayern Munich",
    "bayern munchen": "Bayern Munich",
    "juve": "Juventus",
    "juventus": "Juventus",
    "juventus fc": "Juventus",
    "milan": "AC Milan",
    "ac milan": "AC Milan",
    "inter milan": "Inter Milan",
    "internazionale": "Inter Milan",
    "napoli": "Napoli",
    "roma": "Roma",
    "lazio": "Lazio",
    "galatasaray": "Galatasaray",
    "besiktas": "Besiktas",
    "fenerbahce": "Fenerbahce",
    "ajax": "Ajax",
    "psv": "PSV",
    "porto": "Porto",
    "porto fc": "Porto",
    "sporting cp": "Sporting CP",
    "sporting": "Sporting CP",
    "benfica": "Benfica",
    # Brazilian clubs
    "fla": "Flamengo",
    "flamengo": "Flamengo",
    "palmeiras": "Palmeiras",
    "sao paulo": "Sao Paulo",
    "são paulo": "Sao Paulo",
    "corinthians": "Corinthians",
    "timao": "Corinthians",
    "fluminense": "Fluminense",
    "flu": "Fluminense",
    "vasco": "Vasco",
    # Botafogo RJ (default bare name) vs Botafogo-PB — more specific keys first via exact match
    "botafogo": "Botafogo",
    "botafogo rj": "Botafogo",
    "botafogo fr": "Botafogo",
    "botafogo pb": "Botafogo PB",
    "botafogo-pb": "Botafogo PB",
    "botafogo paraiba": "Botafogo PB",
    "botafogo da paraiba": "Botafogo PB",
    "botafogo-paraiba": "Botafogo PB",
    "belo": "Botafogo PB",
    "confianca": "Confianca",
    "confiança": "Confianca",
    "ad confianca": "Confianca",
    "ad confiança": "Confianca",
    "associacao desportiva confianca": "Confianca",
    "sao bernardo": "Sao Bernardo",
    "são bernardo": "Sao Bernardo",
    "cuiaba": "Cuiaba",
    "cuiabá": "Cuiaba",
    "atletico-mg": "Atletico Mineiro",
    "atlético-mg": "Atletico Mineiro",
    "atletico mineiro": "Atletico Mineiro",
    "atlético mineiro": "Atletico Mineiro",
    "galo": "Atletico Mineiro",
    "cruzeiro": "Cruzeiro",
    "gremio": "Gremio",
    "grêmio": "Gremio",
    "internacional": "Internacional",
    "inter de porto alegre": "Internacional",
    "bragantino": "Bragantino",
    "fortaleza": "Fortaleza",
    "bahia": "Bahia",
    "sport": "Sport Recife",
    "ceara": "Ceara",
    "ceará": "Ceara",
    "santos": "Santos",
    "santos fc": "Santos",
    "peixe": "Santos",
    "athletico-pr": "Athletico-PR",
    "athletico pr": "Athletico-PR",
    "athletico paranaense": "Athletico-PR",
    # National teams (PT → EN)
    "brasil": "Brazil",
    "selecao": "Brazil",
    "seleção": "Brazil",
    "franca": "France",
    "frança": "France",
    "alemanha": "Germany",
    "espanha": "Spain",
    "italia": "Italy",
    "itália": "Italy",
    "holanda": "Netherlands",
    "belgica": "Belgium",
    "bélgica": "Belgium",
    "croacia": "Croatia",
    "croácia": "Croatia",
    "polonia": "Poland",
    "polônia": "Poland",
    "suica": "Switzerland",
    "suíça": "Switzerland",
    "dinamarca": "Denmark",
    "suecia": "Sweden",
    "suécia": "Sweden",
    "noruega": "Norway",
    "marrocos": "Morocco",
    "nigeria": "Nigeria",
    "nigéria": "Nigeria",
    "egito": "Egypt",
    "arabia saudita": "Saudi Arabia",
    "japao": "Japan",
    "japão": "Japan",
    "coreia do sul": "South Korea",
    "coreia": "South Korea",
    "australia": "Australia",
    "austrália": "Australia",
    "estados unidos": "USA",
    "eua": "USA",
    "argentina": "Argentina",
    "uruguai": "Uruguay",
    "chile": "Chile",
    "colombia": "Colombia",
    "colômbia": "Colombia",
    "mexico": "Mexico",
    "méxico": "Mexico",
    "senegal": "Senegal",
    "ghana": "Ghana",
    "gana": "Ghana",
    "russia": "Russia",
    "rússia": "Russia",
    "turquia": "Turkey",
    "ucrania": "Ukraine",
    "ucrânia": "Ukraine",
    "austria": "Austria",
    "áustria": "Austria",
    "hungria": "Hungary",
    "escocia": "Scotland",
    "escócia": "Scotland",
    "wales": "Wales",
    "pais de gales": "Wales",
    "país de gales": "Wales",
    "irlanda": "Ireland",
    "republica tcheca": "Czech Republic",
    "republica checa": "Czech Republic",
    "eslováquia": "Slovakia",
    "eslovaquia": "Slovakia",
    "eslovenia": "Slovenia",
    "eslovênia": "Slovenia",
    "romenia": "Romania",
    "romênia": "Romania",
    "servia": "Serbia",
    "sérvia": "Serbia",
    # Missing European national teams
    "inglaterra": "England",
    "gales": "Wales",
    "grecia": "Greece",
    "grécia": "Greece",
    "finlandia": "Finland",
    "finlândia": "Finland",
    "islandia": "Iceland",
    "islândia": "Iceland",
    "albania": "Albania",
    "albânia": "Albania",
    "georgia": "Georgia",
    "geórgia": "Georgia",
    "azerbaijao": "Azerbaijan",
    "azerbaijão": "Azerbaijan",
    "armenia": "Armenia",
    "armênia": "Armenia",
    "bielorrussia": "Belarus",
    "irlanda do norte": "Northern Ireland",
    "luxemburgo": "Luxembourg",
    "macedonia": "North Macedonia",
    "macedônia": "North Macedonia",
    "norte da macedonia": "North Macedonia",
    "canada": "Canada",
    # South American / CONMEBOL
    "equador": "Ecuador",
    "equadór": "Ecuador",
    "paraguai": "Paraguay",
    "peru": "Peru",
    "venezuela": "Venezuela",
    "bolivia": "Bolivia",
    "bolívia": "Bolivia",
    # Asian / Others
    "coreia do norte": "Korea DPR",
    "corea do norte": "Korea DPR",
    "china": "China",
    "india": "India",
    "índia": "India",
    "africa do sul": "South Africa",
    "áfrica do sul": "South Africa",
    "costa rica": "Costa Rica",
    "nova zelandia": "New Zealand",
    "nova zelândia": "New Zealand",
    # CONMEBOL club sides (minor / alternate names — precheck alias coverage)
    "libertad": "Club Libertad",
    "club libertad": "Club Libertad",
    "libertad asuncion": "Club Libertad",
    "libertad asunción": "Club Libertad",
    "libertad fc": "Club Libertad",
    "club libertad asuncion": "Club Libertad",
    "club libertad asunción": "Club Libertad",
    "universitario": "Universitario de Deportes",
    "universitario de deportes": "Universitario de Deportes",
    "universitario lima": "Universitario de Deportes",
    "universitario de lima": "Universitario de Deportes",
    "tecnico universitario": "Técnico Universitario",
    "técnico universitario": "Técnico Universitario",
    "tecnico universitario de ambato": "Técnico Universitario",
    "técnico universitario de ambato": "Técnico Universitario",
    "tecnico u": "Técnico Universitario",
    "técnico u": "Técnico Universitario",
    # Chilean / Ecuador — exact phrases only (avoid bare "universidad" → Universitario)
    "universidad catolica": "Universidad Catolica",
    "universidad católica": "Universidad Catolica",
    "universidad catolica de chile": "Universidad Catolica",
    "universidad católica de chile": "Universidad Catolica",
    "uc catolica": "Universidad Catolica",
    "uc católica": "Universidad Catolica",
    "catolica de chile": "Universidad Catolica",
    "católica de chile": "Universidad Catolica",
    "ldu": "LDU de Quito",
    "ldu quito": "LDU de Quito",
    "ldu de quito": "LDU de Quito",
    "liga de quito": "LDU de Quito",
    "liga deportiva universitaria": "LDU de Quito",
    "liga deportiva universitaria de quito": "LDU de Quito",
    "leones del norte": "Leones del Norte",
    "deportivo cuenca": "Deportivo Cuenca",
    "cd cuenca": "Deportivo Cuenca",
    # Bolivia — Liga de Fútbol Profesional
    "the strongest": "The Strongest",
    "club the strongest": "The Strongest",
    "oriente petrolero": "Oriente Petrolero",
    "oriente petrolero santa cruz": "Oriente Petrolero",
    # Brazil — Santa Catarina (block Italy Juventus fuzzy)
    "hercilio luz": "Hercilio Luz",
    "hercílio luz": "Hercilio Luz",
    "hercilio luz fc": "Hercilio Luz",
    "hercílio luz fc": "Hercilio Luz",
    "juventus sc": "Juventus SC",
    "juventus jaragua": "Juventus SC",
    "juventus de jaragua": "Juventus SC",
    "juventus jaraguá": "Juventus SC",
    "juventus de jaraguá": "Juventus SC",
    # Ecuador — Barcelona SC / Guayaquil / Católica (block Spain Barcelona fuzzy)
    "barcelona sc": "Barcelona SC",
    "barcelona sporting club": "Barcelona SC",
    "barcelona guayaquil": "Barcelona SC",
    "barcelona de guayaquil": "Barcelona SC",
    "guayaquil city": "Guayaquil City",
    "guayaquil city fc": "Guayaquil City",
    "catolica": "Universidad Catolica del Ecuador",
    "católica": "Universidad Catolica del Ecuador",
    "universidad catolica del ecuador": "Universidad Catolica del Ecuador",
    "universidad católica del ecuador": "Universidad Catolica del Ecuador",
    "universidad catolica ecuador": "Universidad Catolica del Ecuador",
    "universidad católica ecuador": "Universidad Catolica del Ecuador",
    "u catolica ecuador": "Universidad Catolica del Ecuador",
    "u católica ecuador": "Universidad Catolica del Ecuador",
    # USL / US lower divisions
    "one knoxville": "One Knoxville",
    "one knoxville sc": "One Knoxville",
    "knoxville": "One Knoxville",
    "fort wayne": "Fort Wayne FC",
    "fort wayne fc": "Fort Wayne FC",
    "chattanooga": "Chattanooga FC",
    "chattanooga fc": "Chattanooga FC",
    "chattanooga red wolves": "Chattanooga Red Wolves",
    "alta": "Alta FC",
    "alta fc": "Alta FC",
    # Chilean clubs (API often uses Ñublense / O'Higgins)
    "nublense": "Nublense",
    "ñublense": "Nublense",
    "cd nublense": "Nublense",
    "ohiggins": "O'Higgins",
    "o higgins": "O'Higgins",
    "o'higgins": "O'Higgins",
    "cd ohiggins": "O'Higgins",
    "club deportivo ohiggins": "O'Higgins",
}
