"""
Execution Manager — Phase 2/3 scaffolding + Phase 4 Progressive Extraction
+ Phase 5 Progressive Activation PGR-01..PGR-06 + Phase 6 Stabilization
(Mission 043 observability).

Contracts, Step Runner, ports, flag controller, Shadow Mode (observe-only),
thin-report (E1), live (E2), analyze (E3), and live_team_analyze (E4)
progressive extraction behind DEFAULT OFF flags. PGR-01..PGR-06 independent
gates for 1%/5%/10%/25%/50%/100% sole-path canary (DEFAULT OFF). Stabilization
complete; Final Acceptance / definitive Activation NOT started.
"""

from __future__ import annotations

from src.execution_manager.contracts import (
    ANALYZE_FROZEN_ENGINE_ORDER,
    AbortReason,
    ExecutionMode,
    ExecutionRequest,
    ExecutionResult,
    ExecutionStatus,
    FixtureQuality,
    PipelineId,
    StepStatus,
    StepTrace,
)
from src.execution_manager.flags import (
    IllegalEmFlagMatrixError,
    analyze_pipeline_extraction_enabled,
    assert_legal_em_flag_matrix,
    assess_em_mirror_drift,
    effective_em_activation_pct,
    em_flag_snapshot,
    em_flags_all_off,
    em_pipeline_may_route,
    live_pipeline_extraction_enabled,
    live_team_pipeline_extraction_enabled,
    pipeline_enabled,
    rollback_em_all_off,
    rollback_em_shadow_off,
    rollback_em_sole_path_off,
    shadow_enabled,
    thin_pipeline_extraction_enabled,
)
from src.execution_manager.progressive_gate import (
    AUTHORIZED_HIGHEST_GATE,
    AUTHORIZED_OPERATIONAL_MAX_PCT,
    PGR01_PCT,
    PGR01_STAGE,
    PGR02_PCT,
    PGR02_STAGE,
    PGR03_PCT,
    PGR03_STAGE,
    PGR04_PCT,
    PGR04_STAGE,
    PGR05_PCT,
    PGR05_STAGE,
    PGR06_PCT,
    PGR06_STAGE,
    em_pgr_flag_snapshot,
    get_effective_em_activation_pct,
    pgr01_enable_flag,
    pgr02_enable_flag,
    pgr03_enable_flag,
    pgr04_enable_flag,
    pgr05_enable_flag,
    pgr06_enable_flag,
    require_em_pgr01,
    require_em_pgr02,
    require_em_pgr03,
    require_em_pgr04,
    require_em_pgr05,
    require_em_pgr06,
    rollback_em_pgr01_to_off,
    rollback_em_pgr02_to_off,
    rollback_em_pgr03_to_off,
    rollback_em_pgr04_to_off,
    rollback_em_pgr05_to_off,
    rollback_em_pgr06_to_off,
)
from src.execution_manager.router_shim import (
    em_analyze_from_fixture,
    em_analyze_or_legacy,
    em_live_from_feed,
    em_live_or_legacy,
    em_live_team_from_feed,
    em_live_team_or_legacy,
    em_thin_or_legacy,
)
from src.execution_manager.shadow import (
    APPENDIX_A_MANDATORY_KEYS,
    ShadowCompareResult,
    maybe_em_shadow_observe,
    shadow_compare,
    shadow_metrics_snapshot,
)
from src.execution_manager.step_runner import ExecutionManager, StepRunner

__all__ = [
    "ANALYZE_FROZEN_ENGINE_ORDER",
    "APPENDIX_A_MANDATORY_KEYS",
    "AUTHORIZED_HIGHEST_GATE",
    "AUTHORIZED_OPERATIONAL_MAX_PCT",
    "AbortReason",
    "ExecutionManager",
    "ExecutionMode",
    "ExecutionRequest",
    "ExecutionResult",
    "ExecutionStatus",
    "FixtureQuality",
    "IllegalEmFlagMatrixError",
    "PGR01_PCT",
    "PGR01_STAGE",
    "PGR02_PCT",
    "PGR02_STAGE",
    "PGR03_PCT",
    "PGR03_STAGE",
    "PGR04_PCT",
    "PGR04_STAGE",
    "PGR05_PCT",
    "PGR05_STAGE",
    "PGR06_PCT",
    "PGR06_STAGE",
    "PipelineId",
    "ShadowCompareResult",
    "StepRunner",
    "StepStatus",
    "StepTrace",
    "analyze_pipeline_extraction_enabled",
    "assert_legal_em_flag_matrix",
    "assess_em_mirror_drift",
    "effective_em_activation_pct",
    "em_analyze_from_fixture",
    "em_analyze_or_legacy",
    "em_flag_snapshot",
    "em_flags_all_off",
    "em_live_from_feed",
    "em_live_or_legacy",
    "em_live_team_from_feed",
    "em_live_team_or_legacy",
    "em_pipeline_may_route",
    "em_pgr_flag_snapshot",
    "em_thin_or_legacy",
    "get_effective_em_activation_pct",
    "live_pipeline_extraction_enabled",
    "live_team_pipeline_extraction_enabled",
    "maybe_em_shadow_observe",
    "pgr01_enable_flag",
    "pgr02_enable_flag",
    "pgr03_enable_flag",
    "pgr04_enable_flag",
    "pgr05_enable_flag",
    "pgr06_enable_flag",
    "pipeline_enabled",
    "require_em_pgr01",
    "require_em_pgr02",
    "require_em_pgr03",
    "require_em_pgr04",
    "require_em_pgr05",
    "require_em_pgr06",
    "rollback_em_all_off",
    "rollback_em_pgr01_to_off",
    "rollback_em_pgr02_to_off",
    "rollback_em_pgr03_to_off",
    "rollback_em_pgr04_to_off",
    "rollback_em_pgr05_to_off",
    "rollback_em_pgr06_to_off",
    "rollback_em_shadow_off",
    "rollback_em_sole_path_off",
    "shadow_compare",
    "shadow_enabled",
    "shadow_metrics_snapshot",
    "thin_pipeline_extraction_enabled",
]
